---
- block:
  - name: Vimrc
    template: src=vimrc.j2 dest=~/.vimrc mode=0664

  - name: Create ftplugin directory in ~/.vim
    file: path=~/.vim/ftplugin state=directory

  - name: Copy python.vim in ~/.vim/ftplugin
    copy: src=python.vim dest=~/.vim/ftplugin/python.vim mode=0664
    when: vim_complete

  - name: Install Vundle
    git: repo=https://github.com/VundleVim/Vundle.vim.git
         dest=~/.vim/bundle/Vundle.vim
         update=no
    when: vim_complete

  - name: Install Vim plugins
    command: vim +PluginInstall +qall
    when: vim_complete

  - debug: msg="You have chosen vim_solarized option. To complete task - uncommnet 'colorscheme solarized' in your new .vimrc"
    when: vim_solarized and vim_complete

- block:
  - name: Git config
    template: src=gitconfig.j2 dest=~/.gitconfig mode=0664

  - name: Global .gitignore
    copy: src=gitignore dest=~/.gitignore mode=0664

  when: git

- block:
  - name: Custom .tmux.conf
    template: src=tmuxconf.j2 dest=~/.tmux.conf mode=0644

  when: tmux
