---
- name: Install ansible helpers
  yum: name={{ item }} state=latest
  with_items:
    - libselinux-python

- name: Disable SELinux
  selinux: state=disabled

- name: Disable Firewall
  service: name=firewalld state=stopped enabled=no

- name: Install EPEL repo
  yum: name=epel-release state=latest

- name: Install RepoForge (RpmForge) repository
  yum: name=http://pkgs.repoforge.org/rpmforge-release/rpmforge-release-0.5.3-1.el7.rf.x86_64.rpm state=present

- name: Install Rsyslog 8 repository
  command: curl -o /etc/yum.repos.d/rsyslog8.repo http://rpms.adiscon.com/v8-stable/rsyslog.repo creates=/etc/yum.repos.d/rsyslog8.repo

- name: Install yum helpers
  yum: name={{ item }} state=latest
  with_items:
    - deltarpm
    - yum-cron
    - yum-utils

- name: Install common packages with YUM
  yum: name={{item}} state=latest
  with_items: "{{packages}}"

- name: Install compilers (GCC, ..)
  yum: name={{ item }} state=latest
  with_items:
    - gcc 
    - cpp
    - gcc-c++
