---
- name: Include tasks for CentOS 7 hosts
  include: centos7.yml
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version|int >= 7

- name: Include tasks for Fedora hosts
  include: fedora.yml
  when: ansible_distribution == "Fedora" and ansible_distribution_major_version|int >= 22
